# Reference: https://docs.docker.com/compose/compose-file
# Tutorial: https://docs.docker.com/compose/production/
# Multiple files: https://docs.docker.com/compose/extends/#multiple-compose-files
version: '2'
services:
  nginx:
  db:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.development
    volumes:
      - ./server:/myapp
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.development
    volumes:
      - ./client:/myapp

