# Reference: https://docs.docker.com/compose/compose-file
# Tutorial: https://docs.docker.com/compose/production/
# Multiple files: https://docs.docker.com/compose/extends/#multiple-compose-files
version: '2'
services:
  db:
  server:
    env_file: ./server/.env.production
    restart: always
    ports:
      - "4000:4000"
  client:
    env_file: ./client/.env.production
    restart: always
    ports:
      - "3000:3000"
