version: '2'
services:
  db:
    image: postgres
  server:
    build: ./server
    command: bundle exec rails s -p 4000 -b 0.0.0.0
    volumes:
      - ./server:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
  client:
    build: ./client
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - ./client:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - server