# Reference: https://docs.docker.com/compose/compose-file
# Tutorial: https://docs.docker.com/compose/production/
# Multiple files: https://docs.docker.com/compose/extends/#multiple-compose-files
version: '2'
services:
  db:
    image: postgres
  server:
    command: bundle exec rails s -p 4000 -b 0.0.0.0
    depends_on:
      - db
  client:
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    depends_on:
      - server