# Reference: https://docs.docker.com/compose/compose-file
# Tutorial: https://docs.docker.com/compose/production/
# Multiple files: https://docs.docker.com/compose/extends/#multiple-compose-files
version: '2'
services:
  db:
  server:
    volumes:
      - ./server:/myapp
    ports:
      - "4000:4000"
  client:
    volumes:
      - ./client:/myapp
    ports:
      - "3000:3000"

