# Reference: https://docs.docker.com/compose/compose-file
# Tutorial: https://docs.docker.com/compose/production/
# Multiple files: https://docs.docker.com/compose/extends/#multiple-compose-files
version: '2'
services:
  db:
    image: postgres
  server:
    command: bundle exec rails s -p 4000 -b 0.0.0.0
    expose:
      - 4000
    depends_on:
      - db
  client:
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    expose:
      - 3000
    depends_on:
      - server
  nginx:
    build: ./nginx
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes_from:
      - client
      - server
    links:
      - client
      - server
    depends_on:
      - client
      - server
